### ISSUE TITLE
Add more detail about how to start this project properly

### ISSUE THREAD

**Issue by masbossun** [padulkemid/cunyi#3]
found a bit confused about how to start the project properly

**Comment by padulkemid** [comment]
ini masih server doang bossun, bikin tampilannya juga di server iseng aja hahaha, jadi nanti buat web gitu, nah nanti user itu terserah anonymous, disediakan 2 input ( message sama alias ), gunanya apa :
1. message 
 itu bikin pesan curhat kaya buat timeline gitu bossun
2. alias
 ini kaya alterbase gitu (kalo km pernah tau, jaman smp dulu ciwi-ciwi gaul kalo nulis diary suka pake alter [nama samaran gitu] dan ga cuman nama, jadi kaya kepribadian di diarynya itu beda, nah disini dia nulis pake alias nya, contoh kaya kalo anda kan masbossun nama alternya [BUKAN USERNAME ! INI MERUJUK PADA KEPRIBADIAN JUGAAAA])

jadi setelah itu orang bisa nih mau jadi siapapun , cerita apapun, disitu melampiaskan emosi / cerita / curhat / drama / terserahh 

mirip ask.fm tapi tanpa user dan anon

**Comment by masbossun** [comment]
ya, tapi kalo mau contibute tapi ga bisa jalanin project nya di local gimana

**Comment by padulkemid** [comment]
pasang aja itu sequelize sama postgre bossun, ku juga aga bingung gimana biar remote enaknya, db nya mungin kamu bisa saranin, aku kan masih baru ni cuman ide ajaa

**Comment by masbossun** [comment]
nah `pasang` itu ga semua orang (termasuk gw) ngerti pak wkwkwk

**Comment by padulkemid** [comment]
HAHAAHA PUNTENN MAAP BANGETTT BOSSUN HEHEHEHE
